src/project/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from admin_honeypot.admin import honeypot_site
from main import views as main_views
from .sitemaps import site_sitemaps


urlpatterns = [
    url(r'^admin/', include(honeypot_site.urls)),
    url(r'^dladmin/social/', include('social_networks.admin_urls', namespace='admin_social_networks')),
    url(r'^dladmin/autocomplete/', include('libs.autocomplete.urls', namespace='autocomplete')),
    url(r'^dladmin/ckeditor/', include('ckeditor.admin_urls', namespace='admin_ckeditor')),
    url(r'^dladmin/gallery/', include('gallery.admin_urls', namespace='admin_gallery')),
    url(r'^dladmin/users/', include('users.admin_urls', namespace='admin_users')),
    url(r'^dladmin/ctr/', include('admin_ctr.urls', namespace='admin_ctr')),
    url(r'^dladmin/', include(admin.site.urls)),

    url(r'^$', main_views.IndexView.as_view(), name='index'),
    url(r'^404/$', 'django.views.defaults.page_not_found'),
    url(r'^500/$', 'django.views.defaults.server_error'),
    url(r'^away/$', 'libs.away.views.away', name='away'),
    url(r'^jsi18n/$', 'project.views.cached_javascript_catalog', name='jsi18n'),
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': site_sitemaps}),

    url(r'^ckeditor/', include('ckeditor.urls', namespace='ckeditor')),
    url(r'^blocks/', include('attachable_blocks.urls', namespace='blocks')),
    url(r'^placeholder/', include('placeholder.urls', namespace='placeholder')),
    url(r'^social/', include('social_networks.urls', namespace='social_networks')),

    url(r'^contact/', include('contacts.urls', namespace='contacts')),
]


if settings.DEBUG:
    urlpatterns += [
        # Для доступа к MEDIA-файлам при разработке
        url(
            r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            kwargs={'document_root': settings.MEDIA_ROOT}
        ),
        url(
            r'^static/(?P<path>.*)$',
            'django.views.static.serve',
            kwargs={'document_root': settings.STATIC_ROOT}
        ),
    ]

src/templates/suit/change_form.html
{% extends 'admin/change_form.html' %}

{% block extrajs %}
  {{ block.super }}

  {% if suit_tabs %}
    <script type="text/javascript">
      (function($) {
        $(function() {
          $('#suit_form_tabs').suit_form_tabs();
        });
      }(Suit.$))
    </script>
  {% endif %}
{% endblock extrajs %}

{% block field_sets %}
  {% for fieldset in adminform %}
    {% if fieldset.fields %}
      {% include "admin/includes/fieldset.html" %}
    {% endif %}
  {% endfor %}
{% endblock field_sets %}

{% block suit_form_tabs %}
  {% if suit_tabs %}
    <ul id="suit_form_tabs" class="nav nav-tabs nav-tabs-suit" data-tab-prefix="suit-tab">
      {% for tab in suit_tabs %}
        <li><a href="#{{ tab.0 }}">{{ tab.1 }}</a></li>
      {% endfor %}
    </ul>
  {% endif %}
{% endblock suit_form_tabs %}

src/templates/suit/menu.html
{#{% load sitetree %}#}
{% load i18n my_suit_menu %}
{% load url from suit_compat %}

<div class="left-nav" id="left-nav">
  <ul>
    {% block menu_home %}
      {% url 'admin:index' as index_url %}
      <li{% if index_url == request.path %} class="active"{% endif %}>
        <a href="{{ index_url }}"><i class="icon-home"></i>{% trans 'Welcome' %}
        </a>
      </li>
    {% endblock %}

    {% get_menu request as app_list %}
    {% if app_list %}
      {% for app in app_list %}
        {% if app.separator %}
          <li class="separator"></li>
        {% else %}
          <li{{ app.is_active|yesno:' class=active,' }}>
            <a href="{{ app.url }}"{{ app.blank|yesno:' target=_blank,' }}>
              <i class="{% firstof app.icon 'icon-chevron-right' %}"></i>
              {% trans app.label|capfirst %}
            </a>

            {% if app.models %}
              {% include 'suit/submenu.html' with models=app.models %}
            {% endif %}

          </li>
        {% endif %}
      {% endfor %}
    {% endif %}
  </ul>
</div>

src/templates/suit/submenu.html
<ul>
  {% for model in models %}
    <li{{ model.is_active|yesno:' class=active,' }}>
      <a href="{{ model.url }}"{{ model.blank|yesno:' target=_blank,' }}>{{ model.label }}</a>

      {% if model.models %}
        {% include 'suit/submenu.html' with models=model.models %}
      {% endif %}
    </li>
  {% endfor %}
</ul>